function ok = test_aos_report_coverage_hf3_5()
% TEST_AOS_REPORT_COVERAGE_HF3_5 Cobertura de exportadores con tablas.
  ok = true;
  raiz = fileparts(fileparts(fileparts(mfilename('fullpath'))));
  checks = { ...
    'src/utilidades/intercambio/exportar_aosrpt.m','aos_report_prepare_tables'; ...
    'src/utilidades/intercambio/aos_report_dispatcher.m','aos_report_prepare_tables'; ...
    'src/utilidades/intercambio/exportar_aosrpt_grafico.m','aos_report_prepare_tables'; ...
    'src/utilidades/intercambio/exportar_aosrpt_mandriles.m','aos_report_prepare_tables'; ...
    'src/sensibilidad/sens_exportar_resultados.m','aos_report_prepare_tables'; ...
    'src/utilidades/intercambio/aos_exportar_sensibilidad_core.m','aos_report_prepare_tables'; ...
    'src/core/BES2/bes2_exportar_reporte.m','aos_report_prepare_tables'; ...
    'src/core/BES3/bes3_exportar_reporte.m','aos_report_prepare_tables'; ...
    'src/core/BES3/bes3_exportar_comparacion_core.m','aos_report_prepare_tables'; ...
    'src/core/CGF/cgf_exportar_reporte.m','aos_report_prepare_tables'; ...
    'src/core/EGF/egf_exportar_reporte.m','aos_report_prepare_tables'; ...
    'src/core/BM/gibbs_foundation3/gibbs3_report_context.m','gibbs3_report_build_tables'; ...
    'src/modulos/cad_topo/aos_aoscad_escribir.m','aos_aoscad_report_composition'; ...
    'src/utilidades/intercambio/importar_aosrpt.m','aos_report_print_native_tables'};
  for i = 1:size(checks,1)
    ruta = fullfile(raiz,checks{i,1});
    if exist(ruta,'file') ~= 2
      fprintf(2,'FALTA %s\n',checks{i,1}); ok = false; continue;
    endif
    txt = fileread(ruta);
    if isempty(strfind(txt,checks{i,2}))
      fprintf(2,'FALLO cobertura %s -> %s\n',checks{i,1},checks{i,2});
      ok = false;
    endif
  endfor
  if ok, fprintf('RESULTADO: test_aos_report_coverage_hf3_5 APROBADO\n'); endif
endfunction
