function snap = aos_capturar_canonicos_runtime(cfg)
% Captura los campos canonicos que un menu, solver o sensibilidad puede
% modificar durante la sesion. Los aliases de unidades del .aosdat no deben
% volver a pisar estos valores al normalizar una configuracion ya activa.
% GNU Octave es el entorno objetivo.

  snap = struct();
  if nargin < 1 || ~isstruct(cfg), return; end

  campos = { ...
    'P_res','P_wh','P_iny_sup','P_b','P_intake_min','P_sep', ...
    'IP','factor_IP_residual','factor_VLP','WC','GLR','API','gamma_g', ...
    'T_sup','T_fondo','rho_o','rho_w','rho_g_std','R_gas', ...
    'diam_tbg','ID_csg','rugosidad','OD_tbg', ...
    'D_iny','D_levantamiento','D_valvula','D_eductor', ...
    'D_bomba','D_intake','D_res','D_midperf','D_packer', ...
    'D_punzados_tope','D_punzados_base', ...
    'Q_iny','Qiny','Qiny_plot','qiny_modo', ...
    'A_n','d_t','a_eductor','b_eductor','eta_n','eta_t','eta_d', ...
    'modelo_IPR','modelo_VLP', ...
    'curva_bomba_file','frecuencia','frecuencia_base','num_etapas', ...
    'T_max_motor','eficiencia_motor','cp_fluido','velocidad_min_refrig', ...
    'voltaje_motor','IR_base','factor_envejecimiento','mu_o', ...
    'D_bomba_mm','S_carrera','N_velocidad','eta_vol','eta_mecanica_BM', ...
    'tipo_unidad','modelo_unidad_BM','material_varillas','tuberia_anclada', ...
    'usar_gibbs_BM','gibbs_n_t','gibbs_n_ciclos','gibbs_n_nodos', ...
    'gibbs_amortiguamiento','gibbs_metodo_forward','slip_bomba', ...
    'eficiencia_valvulas','friccion_bomba_N','nombre_pozo','archivo_aosdat', ...
    'jgl_modo','jgl_tol_Q_rel','jgl_tol_P_bar','jgl_tol_dP_bar', ...
    'jgl_min_iter','jgl_max_iter','jgl_alpha','jgl_eta_transfer', ...
    'jgl_factor_gas_liquido','jgl_geometria_modo' ...
  };

  for i = 1:length(campos)
    c = campos{i};
    if isfield(cfg, c)
      snap.(c) = cfg.(c);
    end
  end
end
