function ok = VERIFICAR_AOS_0_2_0_DEV1(profundo)
% VERIFICAR_AOS_0_2_0_DEV1 Verifica la primera baseline AOS 0.2.0.
% Integra AOS 0.1.9 R2 HF3.4-CAD-R16 y composicion de tablas HF3.5.
  if nargin < 1, profundo = false; endif
  raiz = fileparts(mfilename('fullpath'));
  cd(raiz);
  addpath(raiz, '-begin');
  addpath(fullfile(raiz, 'src'), '-begin');
  iniciar_aos(true);

  fprintf('\n================================================================\n');
  fprintf(' VERIFICACION AOS SUITE 0.2.0 DEV1\n');
  fprintf(' Baseline 0.1.9 R2 HF3.4-CAD-R16 + HF3.5 + SENS-GLJGL-03\n');
  fprintf('================================================================\n');
  ok = true;

  ok = verificar_version_local(raiz, ok);

  requeridos = { ...
    'AOS.m', 'AOS_VERSION.txt', 'VERSION', 'src/iniciar_aos.m', ...
    'src/menu/AOS_app.m', 'src/menu/aos_suite_registro_productos.m', ...
    'src/menu/AOS_menu_environmental.m', ...
    'VERIFICAR_SENS_GLJGL_01.m', 'VERIFICAR_SENS_GLJGL_02.m', ...
    'VERIFICAR_SENS_GLJGL_03.m', ...
    'src/sensibilidad/sens_firma_config_gl_jgl.m', ...
    'src/sensibilidad/sens_validar_base_gl_jgl.m', ...
    'src/sensibilidad/sens_validar_punto_gl.m', ...
    'src/sensibilidad/sens_validar_punto_jgl.m', ...
    'src/sensibilidad/sens_gl_evaluar_punto.m', ...
    'src/sensibilidad/sens_jgl_evaluar_punto.m', ...
    'src/sensibilidad/sens_menu_tratamiento_curva.m', ...
    'src/sensibilidad/sens_seleccionar_grado_polinomio.m', ...
    'src/sensibilidad/sens_ajuste_polinomico.m', ...
    'src/sensibilidad/sens_validar_ajuste_polinomico.m', ...
    'src/sensibilidad/sens_verificar_optimo_polinomico.m', ...
    'src/sensibilidad/sens_imprimir_diagnostico_polinomio.m', ...
    'src/core/JGL/jgl_modo_condicion_motriz.m', ...
    'src/core/JGL/jgl_deltaP_cinetica_qiny.m', ...
    'src/core/JGL/jgl_condicion_motriz.m', ...
    'src/sensibilidad/sens_menu_condicion_motriz_jgl.m', ...
    'src/sensibilidad/sens_jgl_construir_presiones.m', ...
    'src/sensibilidad/sens_jgl_imprimir_presiones.m', ...
    'src/sensibilidad/sens_jgl_graficar_presiones.m', ...
    'src/sensibilidad/sens_jgl_limite_presion.m', ...
    'src/tests/test_sens_gljgl01_contrato_estatico.m', ...
    'src/tests/test_sens_gljgl01_validacion_estados.m', ...
    'src/tests/test_sens_gljgl01_paridad_gl.m', ...
    'src/tests/test_sens_gljgl01_metodo_uniforme_jgl.m', ...
    'src/tests/test_sens_gljgl02_contrato_estatico.m', ...
    'src/tests/test_sens_gljgl02_menu_explicito.m', ...
    'src/tests/test_sens_gljgl02_discreto_sin_polinomio.m', ...
    'src/tests/test_sens_gljgl02_informativo_no_recomienda.m', ...
    'src/tests/test_sens_gljgl02_polinomio_grado5.m', ...
    'src/tests/test_sens_gljgl02_grado_automatico.m', ...
    'src/tests/test_sens_gljgl02_mascaras_curva_optimo.m', ...
    'src/tests/test_sens_gljgl02_discontinuidad.m', ...
    'src/tests/test_sens_gljgl03_contrato_estatico.m', ...
    'src/tests/test_sens_gljgl03_condicion_motriz_derivada.m', ...
    'src/tests/test_sens_gljgl03_presion_disponible.m', ...
    'src/tests/test_sens_gljgl03_eductor_derivado_no_bloqueado.m', ...
    'src/tests/test_sens_gljgl03_inversion_columna.m', ...
    'src/tests/test_sens_gljgl03_limite_presion.m', ...
    'src/tests/test_sens_gljgl03_barrido_derivado_jgl.m', ...
    'src/roadmap/aos_release_0_2_0_dev1.json', ...
    'src/roadmap/aos_hotfix_sens_gljgl_01.json', ...
    'src/roadmap/aos_hotfix_sens_gljgl_02.json', ...
    'src/roadmap/aos_hotfix_sens_gljgl_03.json', ...
    'src/roadmap/aos_workbenches_0_2_0_dev1.json', ...
    'src/roadmap/aos_services_0_2_0_dev1.json', ...
    'src/roadmap/aos_solvers_0_2_0_dev1.json', ...
    'src/roadmap/aos_roadmap_0_2_0_dev1.json', ...
    'src/roadmap/aos_frame_ribbon_contract_0_2_0.json', ...
    'src/roadmap/aos_report_tables_contract_hf3_5.json', ...
    'src/utilidades/reportes/aos_report_configure_tables.m', ...
    'src/utilidades/reportes/aos_report_apply_profile.m', ...
    'src/utilidades/reportes/aos_report_prepare_tables.m', ...
    'src/utilidades/reportes/aos_report_write_manifest.m', ...
    'src/utilidades/reportes/aos_report_parse_native_tables.m', ...
    'src/utilidades/reportes/aos_report_print_native_tables.m', ...
    'src/utilidades/intercambio/aos_rpt_escribir_tablas.m', ...
    'src/core/BM/gibbs_foundation3/gibbs3_report_build_tables.m', ...
    'src/core/BES2/bes2_report_build_tables.m', ...
    'src/core/BES3/bes3_report_build_tables.m', ...
    'src/core/CGF/cgf_report_build_tables.m', ...
    'src/modulos/cad_topo/aos_aoscad_report_composition.m', ...
    'src/modulos/cad_topo/aos_aoscad_escribir.m', ...
    'src/modulos/cad_topo/aos_aoscad_generar_recursos_visuales.m', ...
    'src/modulos/cad_topo/aos_cad_sincronizar_2d_3d.m', ...
    'src/modulos/cad_topo/VERSION_AOSCAD.txt', ...
    'src/services/geometry_3d/aos_escena_federada.m', ...
    'src/tests/test_aos_report_composition_hf3_5.m', ...
    'src/tests/test_aos_report_module_tables_hf3_5.m', ...
    'src/tests/test_aos_report_sensitivity_hf3_5.m', ...
    'src/tests/test_aos_aoscad_report_composition_hf3_5.m', ...
    'src/tests/test_aos_report_coverage_hf3_5.m', ...
    'src/tests/test_aos_environmental_runtime_shell_env02.m', ...
    'AOS_0_2_0_DEV1_CONTEXTO_COMPLETO.md', ...
    'documentos/AOS_0_2_0_DEV1_CONTEXTO_INTEGRAL.docx'};

  for i = 1:numel(requeridos)
    ruta = fullfile(raiz, requeridos{i});
    if exist(ruta, 'file') == 2
      fprintf('OK   %s\n', requeridos{i});
    else
      fprintf(2, 'FALTA %s\n', requeridos{i});
      ok = false;
    endif
  endfor

  ok = verificar_integracion_cad_reportes_local(raiz, ok);
  ok = verificar_json_local(raiz, ok);
  ok = verificar_octave_only_local(raiz, ok);

  pruebas = { ...
    'test_aos_report_composition_hf3_5', ...
    'test_aos_report_module_tables_hf3_5', ...
    'test_aos_report_sensitivity_hf3_5', ...
    'test_aos_aoscad_report_composition_hf3_5', ...
    'test_aos_report_coverage_hf3_5', ...
    'test_aos_environmental_runtime_shell_env02', ...
    'test_sens_gljgl01_contrato_estatico', ...
    'test_sens_gljgl01_validacion_estados', ...
    'test_sens_gljgl01_paridad_gl', ...
    'test_sens_gljgl02_contrato_estatico', ...
    'test_sens_gljgl02_menu_explicito', ...
    'test_sens_gljgl02_discreto_sin_polinomio', ...
    'test_sens_gljgl02_informativo_no_recomienda', ...
    'test_sens_gljgl02_polinomio_grado5', ...
    'test_sens_gljgl02_grado_automatico', ...
    'test_sens_gljgl02_mascaras_curva_optimo', ...
    'test_sens_gljgl02_discontinuidad', ...
    'test_sens_gljgl03_contrato_estatico', ...
    'test_sens_gljgl03_condicion_motriz_derivada', ...
    'test_sens_gljgl03_presion_disponible', ...
    'test_sens_gljgl03_eductor_derivado_no_bloqueado', ...
    'test_sens_gljgl03_inversion_columna', ...
    'test_sens_gljgl03_limite_presion'};
  for i = 1:numel(pruebas)
    ok = ejecutar_test_local(pruebas{i}, ok);
  endfor

  try
    r = VERIFICAR_AOS_0_1_9(false);
    ok = ok && ~isempty(r) && logical(r);
  catch err
    fprintf(2, 'FALLO verificacion de nucleos heredados: %s\n', err.message);
    ok = false;
  end_try_catch

  if profundo
    try
      r = VERIFICAR_AOS_0_1_9(true);
      ok = ok && ~isempty(r) && logical(r);
    catch err
      fprintf(2, 'FALLO campana integral heredada: %s\n', err.message);
      ok = false;
    end_try_catch

    try
      r = VERIFICAR_AOSCAD_0_0_1_DEV1(true);
      ok = ok && ~isempty(r) && logical(r);
    catch err
      fprintf(2, 'FALLO campana AOSCAD R16: %s\n', err.message);
      ok = false;
    end_try_catch

    ok = ejecutar_test_local('test_sens_gljgl01_metodo_uniforme_jgl', ok);

    pruebas_r16 = { ...
      'test_aos_aoscad_recursos_visuales', ...
      'test_aos_cad_sincronizacion_2d_3d', ...
      'test_aos_cad_overlay_3d', ...
      'test_aos_escena_federada'};
    for i = 1:numel(pruebas_r16)
      if exist(pruebas_r16{i}, 'file') == 2
        ok = ejecutar_test_local(pruebas_r16{i}, ok);
      else
        fprintf(2, 'FALTA prueba R16 %s\n', pruebas_r16{i});
        ok = false;
      endif
    endfor
  endif

  fprintf('\n================================================================\n');
  if ok
    fprintf('RESULTADO: AOS SUITE 0.2.0 DEV1 APROBADO\n');
  else
    fprintf(2, 'RESULTADO: AOS SUITE 0.2.0 DEV1 NO APROBADO\n');
  endif
  fprintf('================================================================\n');
endfunction

function ok = verificar_version_local(raiz, ok)
  ruta = fullfile(raiz, 'VERSION');
  if exist(ruta, 'file') ~= 2
    fprintf(2, 'FALLO: VERSION ausente\n');
    ok = false; return;
  endif
  v = strtrim(fileread(ruta));
  if strcmp(v, '0.2.0-DEV1')
    fprintf('OK   VERSION %s\n', v);
  else
    fprintf(2, 'FALLO: VERSION esperada 0.2.0-DEV1; encontrada %s\n', v);
    ok = false;
  endif
endfunction

function ok = verificar_integracion_cad_reportes_local(raiz, ok)
  ruta = fullfile(raiz, 'src', 'modulos', 'cad_topo', 'aos_aoscad_escribir.m');
  if exist(ruta, 'file') ~= 2, ok = false; return; endif
  txt = fileread(ruta);
  if isempty(strfind(txt, 'aos_aoscad_report_composition'))
    fprintf(2, 'FALLO: AOSCAD no integra composicion transversal de tablas\n'); ok = false;
  else
    fprintf('OK   AOSCAD integra composicion transversal de tablas\n');
  endif
  if isempty(strfind(txt, 'aos_aoscad_generar_recursos_visuales'))
    fprintf(2, 'FALLO: se perdio generacion de recursos visuales R16\n'); ok = false;
  else
    fprintf('OK   AOSCAD conserva recursos visuales R16\n');
  endif
  ver = fullfile(raiz, 'src', 'modulos', 'cad_topo', 'VERSION_AOSCAD.txt');
  if exist(ver, 'file') == 2
    t = fileread(ver);
    if isempty(strfind(t, 'AOSCAD-0.0.1-DEV1-R16'))
      fprintf(2, 'FALLO: AOSCAD integrado no es R16\n'); ok = false;
    else
      fprintf('OK   AOSCAD R16 preservado\n');
    endif
  endif
endfunction

function ok = verificar_json_local(raiz, ok)
  archivos = { ...
    'src/roadmap/aos_release_0_2_0_dev1.json', ...
    'src/roadmap/aos_hotfix_sens_gljgl_01.json', ...
    'src/roadmap/aos_hotfix_sens_gljgl_02.json', ...
    'src/roadmap/aos_hotfix_sens_gljgl_03.json', ...
    'src/roadmap/aos_workbenches_0_2_0_dev1.json', ...
    'src/roadmap/aos_services_0_2_0_dev1.json', ...
    'src/roadmap/aos_solvers_0_2_0_dev1.json', ...
    'src/roadmap/aos_roadmap_0_2_0_dev1.json', ...
    'src/roadmap/aos_frame_ribbon_contract_0_2_0.json', ...
    'src/roadmap/aos_report_tables_contract_hf3_5.json'};
  if exist('jsondecode', 'builtin') ~= 5 && exist('jsondecode', 'file') ~= 2
    fprintf(2, 'FALLO: jsondecode no disponible en GNU Octave\n');
    ok = false; return;
  endif
  for i = 1:numel(archivos)
    ruta = fullfile(raiz, archivos{i});
    try
      jsondecode(fileread(ruta));
      fprintf('OK   JSON %s\n', archivos{i});
    catch err
      fprintf(2, 'FALLO JSON %s: %s\n', archivos{i}, err.message);
      ok = false;
    end_try_catch
  endfor
endfunction

function ok = verificar_octave_only_local(raiz, ok)
  mats = listar_extension_local(raiz, '.mat');
  if isempty(mats)
    fprintf('OK   arquitectura sin archivos .mat\n');
  else
    fprintf(2, 'FALLO: archivos .mat encontrados:\n');
    for i = 1:numel(mats), fprintf(2, '  %s\n', mats{i}); endfor
    ok = false;
  endif

  dups = duplicados_m_local(fullfile(raiz, 'src'));
  if isempty(dups)
    fprintf('OK   sin nombres .m duplicados dentro de src\n');
  else
    fprintf(2, 'FALLO: nombres .m duplicados dentro de src:\n');
    for i = 1:numel(dups), fprintf(2, '  %s\n', dups{i}); endfor
    ok = false;
  endif
endfunction

function ok = ejecutar_test_local(nombre, ok)
  try
    iniciar_aos(true); rehash();
    if exist(nombre, 'file') ~= 2
      fprintf(2, 'FALLO: selftest no encontrado: %s\n', nombre);
      ok = false; return;
    endif
    r = feval(nombre);
    if ~isempty(r) && logical(r)
      fprintf('OK   selftest %s\n', nombre);
    else
      fprintf(2, 'FALLO: selftest sin aprobacion: %s\n', nombre);
      ok = false;
    endif
  catch err
    fprintf(2, 'FALLO selftest %s: %s\n', nombre, err.message);
    ok = false;
  end_try_catch
endfunction

function lista = listar_extension_local(carpeta, extension)
  lista = {};
  d = dir(carpeta);
  for i = 1:numel(d)
    if strcmp(d(i).name, '.') || strcmp(d(i).name, '..'), continue; endif
    ruta = fullfile(carpeta, d(i).name);
    if d(i).isdir
      sub = listar_extension_local(ruta, extension);
      lista = [lista, sub]; %#ok<AGROW>
    else
      [~,~,e] = fileparts(d(i).name);
      if strcmpi(e, extension), lista{end+1} = ruta; endif %#ok<AGROW>
    endif
  endfor
endfunction

function dups = duplicados_m_local(carpeta)
  rutas = listar_m_local(carpeta);
  nombres = cell(1, numel(rutas));
  for i = 1:numel(rutas)
    [~, nombres{i}] = fileparts(rutas{i});
    nombres{i} = lower(nombres{i});
  endfor
  dups = {};
  unicos = unique(nombres);
  for i = 1:numel(unicos)
    idx = find(strcmp(nombres, unicos{i}));
    if numel(idx) > 1
      for j = 1:numel(idx), dups{end+1} = rutas{idx(j)}; endfor %#ok<AGROW>
    endif
  endfor
endfunction

function rutas = listar_m_local(carpeta)
  rutas = {};
  d = dir(carpeta);
  for i = 1:numel(d)
    if strcmp(d(i).name, '.') || strcmp(d(i).name, '..'), continue; endif
    ruta = fullfile(carpeta, d(i).name);
    if d(i).isdir
      rutas = [rutas, listar_m_local(ruta)]; %#ok<AGROW>
    else
      [~,~,e] = fileparts(d(i).name);
      if strcmpi(e, '.m'), rutas{end+1} = ruta; endif %#ok<AGROW>
    endif
  endfor
endfunction
