function sol = bes3_solver(param)
% Solver BES3: barrido, multiples raices y recirculacion capilar acoplada.
% DEV5 incorpora diagnostico de recirculacion respecto del caudal nominal
% efectivo y operacion diferenciada de las secciones inferior/superior.
  p=bes3_defaults(param);
  if p.frecuencia<=0 || strcmpi(p.bes3_estado_bomba,'apagada')
    sol=bes3_solver_flujo_natural(p);return;
  endif
  p.bes3_estado_bomba='encendida';p.bes3_frecuencia_efectiva_Hz=p.frecuencia;
  p.bes3_frecuencia_solicitada_Hz=p.frecuencia;
  bomba=bes2_cargar_bomba(p);curva=bes2_curva_bomba(p,bomba);
  [Qipr,Pwf_fun]=ipr(p,p.modelo_IPR);
  qlo=max(min(curva.Q_m3_s),0);qhi=min(max(curva.Q_m3_s),Qipr);
  n=max(round(p.bes3_n_puntos_solver),81);
  if qhi<=qlo,sol=vacia_local(p,bomba,curva,'DOMINIO_VACIO');return;endif
  q=linspace(qlo,qhi,n);R=NaN(size(q));ev=cell(size(q));
  for i=1:numel(q)
    ev{i}=bes3_evaluar_punto(q(i),p,curva,Pwf_fun);
    if ev{i}.valido,R(i)=ev{i}.residuo;endif
  endfor
  roots=[];revals={};
  for i=1:numel(q)-1
    if isfinite(R(i))&&abs(R(i))<=p.bes3_tol_P_bar*1e5
      roots(end+1)=q(i);revals{end+1}=ev{i};
    elseif isfinite(R(i))&&isfinite(R(i+1))&&R(i)*R(i+1)<0
      [qr,er]=bisect_local(q(i),q(i+1),p,curva,Pwf_fun);roots(end+1)=qr;revals{end+1}=er;
    endif
  endfor
  if isempty(roots)
    idx=find(isfinite(R));if isempty(idx),sol=vacia_local(p,bomba,curva,'SIN_PUNTOS_VALIDOS');return;endif
    [~,j]=min(abs(R(idx)));best=ev{idx(j)};
    if all(R(idx)>0),estado='SIN_CRUCE_EXCESO_CAPACIDAD_LIMITADO_POR_IPR_O_DOMINIO';
    elseif all(R(idx)<0),estado='SIN_CRUCE_CAPACIDAD_BOMBA_INSUFICIENTE';
    else,estado='SIN_CRUCE_NUMERICO';endif
    sol=armar_local(p,bomba,curva,best,roots,q,R,ev,estado,false);return;
  endif
  scores=Inf(numel(roots),1);
  for k=1:numel(roots),scores(k)=score_raiz_local(revals{k},curva,p);endfor
  [~,ib]=min(scores);sol=armar_local(p,bomba,curva,revals{ib},roots,q,R,ev,'CONVERGIDO',true);
endfunction

function [qr,er]=bisect_local(a,b,p,c,pwf)
  ea=bes3_evaluar_punto(a,p,c,pwf);fa=ea.residuo;qr=a;er=ea;
  for k=1:p.bes3_max_biseccion
    m=0.5*(a+b);em=bes3_evaluar_punto(m,p,c,pwf);if ~em.valido,b=m;continue;endif
    fm=em.residuo;qr=m;er=em;if abs(fm)<=p.bes3_tol_P_bar*1e5,break;endif
    if fa*fm<=0,b=m;else,a=m;fa=fm;endif
  endfor
endfunction
function sc=score_raiz_local(e,c,p)
  d=bes3_diagnostico_recirculacion(c,e.bomba_secciones,e.recirculacion,p,e.Q_m3_d);
  dist_inf=abs(d.BEP_inferior_pct-100)/100;if ~isfinite(dist_inf),dist_inf=10;endif
  dist_sup=abs(d.BEP_superior_pct-100)/100;if ~isfinite(dist_sup),dist_sup=10;endif
  fuera=double(~strcmp(d.estado_secciones,'AMBAS_SECCIONES_DENTRO_RANGO'));
  cool=double(~e.recirculacion.cumple && e.recirculacion.Q_requerido_m3_s>0);
  elec=double(~strcmp(e.electrico.estado,'OK'));
  gas=double(e.fluido.gvf_bomba>=p.bes2_gvf_lock);
  recbad=double(~d.cumple_diseno && e.recirculacion.Q_recirc_m3_d>p.bes3_tol_produccion_m3_d);
  sinprod=double(e.Q_m3_d<=p.bes3_tol_produccion_m3_d);
  sc=0.5*(dist_inf+dist_sup)+2*fuera+4*cool+3*elec+4*gas+3*recbad+5*sinprod;
endfunction
function sol=armar_local(p,b,c,e,roots,q,R,ev,estado,conv)
  qd=e.Q_m3_d;qp=e.Q_pump_neto_m3_d;
  drec=bes3_diagnostico_recirculacion(c,e.bomba_secciones,e.recirculacion,p,qd);
  pb=drec.BEP_superior_pct;range=drec.rango_superior_estado;
  if e.fluido.gvf_bomba>=p.bes2_gvf_lock,gas='RIESGO_GAS_LOCK';elseif e.fluido.gvf_bomba>=p.bes2_gvf_interferencia,gas='INTERFERENCIA_GAS';else,gas='GAS_ADMISIBLE';endif
  req=e.recirculacion.Q_requerido_m3_s>p.bes3_tol_refrigeracion_frac*max(e.recirculacion.Q_min_refrig_m3_s,1e-12);
  cool_ok=(~req)||e.recirculacion.cumple;
  prod_ok=qd>p.bes3_tol_produccion_m3_d;
  aceptado=conv&&strcmp(drec.estado_secciones,'AMBAS_SECCIONES_DENTRO_RANGO')&&~strcmp(gas,'RIESGO_GAS_LOCK')&& ...
    strcmp(e.electrico.estado,'OK')&&cool_ok&&drec.cumple_diseno&&prod_ok;
  s=series_local(ev);[vlp_sel,vlp_eff]=modelos_local(p);
  if conv,punto_tipo='CRUCE_NODAL';else,punto_tipo='REFERENCIA_MENOR_RESIDUO_SIN_CRUCE';endif
  fstate=frecuencia_estado_local(p);
  estado_operativo=drec.estado_operativo;
  if conv&&strcmp(estado_operativo,'RECIRCULACION_INTERNA_SIN_PRODUCCION')
    estado='CONVERGIDO_RECIRCULACION_INTERNA_SIN_PRODUCCION';
  elseif conv&&strcmp(estado_operativo,'SIN_PRODUCCION_NETA')
    estado='CONVERGIDO_SIN_PRODUCCION_NETA';
  endif
  sol=struct('version',p.bes3_version,'estado_validacion',p.bes3_estado_validacion,'estado',estado, ...
    'modo_operacion','BOMBA_ENCENDIDA','estado_bomba','ENCENDIDA','modo_frecuencia',p.bes3_modo_frecuencia, ...
    'frecuencia_configurada_Hz',p.bes3_frecuencia_configurada_Hz,'frecuencia_solicitada_Hz',p.frecuencia, ...
    'frecuencia_efectiva_Hz',p.frecuencia,'frecuencia_estado',fstate, ...
    'convergido',conv,'punto_operacion_valido',conv,'punto_tipo',punto_tipo, ...
    'aceptado_preliminar',aceptado,'aceptado',false,'param',p,'bomba',b,'curva',c, ...
    'modelo_IPR',p.modelo_IPR,'modelo_VLP',vlp_sel,'vlp_efectivo',vlp_eff, ...
    'punto',e,'Ql_m3_d',qd,'Qo_m3_d',qd*(1-p.WC),'Qg_total_Sm3_d',e.Ql*p.GLR*86400, ...
    'Q_pump_neto_m3_d',qp,'Q_recirc_m3_d',e.recirculacion.Q_recirc_m3_d,'percent_BEP',pb, ...
    'num_etapas_total',drec.num_etapas_total,'etapa_toma',drec.etapa_toma, ...
    'Q_nominal_efectivo_m3_d',drec.Q_nominal_efectivo_m3_d, ...
    'Q_recirc_pct_nominal',drec.Q_recirc_pct_nominal, ...
    'Q_recirc_max_diseno_m3_d',drec.Q_recirc_max_diseno_m3_d, ...
    'Q_etapas_inferiores_m3_d',drec.Q_etapas_inferiores_m3_d, ...
    'Q_etapas_superiores_m3_d',drec.Q_etapas_superiores_m3_d, ...
    'BEP_inferior_pct',drec.BEP_inferior_pct,'BEP_superior_pct',drec.BEP_superior_pct, ...
    'estado_diseno_recirculacion',drec.estado_diseno,'estado_operativo_recirculacion',drec.estado_operativo, ...
    'diagnostico_recirculacion',drec,'margen_nodal_bar',e.residuo/1e5, ...
    'rango_estado',range,'rango_inferior_estado',drec.rango_inferior_estado, ...
    'rango_superior_estado',drec.rango_superior_estado,'gas_estado',gas, ...
    'refrigeracion_estado',e.recirculacion.estado,'electrico',e.electrico, ...
    'geometria',e.geometria,'recirculacion',e.recirculacion, ...
    'raices_m3_d',roots*86400,'n_raices',numel(roots),'barrido_Q_m3_d',q*86400, ...
    'barrido_residuo_bar',R/1e5,'barrido_Pwf_bar',s.Pwf/1e5, ...
    'barrido_Pintake_bar',s.Pintake/1e5,'barrido_Pdesc_disponible_bar',s.Pdisp/1e5, ...
    'barrido_Pdesc_requerida_bar',s.Preq/1e5,'barrido_dP_bomba_bar',s.dPpump/1e5, ...
    'barrido_dP_bomba_apagada_bar',zeros(size(q)));
  sol.semaforos=bes3_semaforos(sol);
  sol.diagnostico=sprintf('Solver=%s | Punto=%s | IPR=%s | VLP=%s/%s | Secciones=%s | Recirculacion=%s (%.2f%% de Qnom; limite %.2f%%) | Operacion=%s | Gas=%s | Refrigeracion=%s | Electrico=%s | Preliminar=%d | Validacion=%s', ...
    estado,punto_tipo,p.modelo_IPR,vlp_sel,vlp_eff,drec.estado_secciones,drec.estado_diseno,drec.Q_recirc_pct_nominal, ...
    drec.limite_recirc_pct_nominal,drec.estado_operativo,gas,e.recirculacion.estado,e.electrico.estado,aceptado,p.bes3_estado_validacion);
endfunction
function s=vacia_local(p,b,c,e)
  [vlp_sel,vlp_eff]=modelos_local(p);
  d=struct('num_etapas_total',p.num_etapas,'etapa_toma',0,'n_etapas_inferiores',0,'n_etapas_superiores',p.num_etapas, ...
    'Q_nominal_efectivo_m3_d',num_local(c,'Q_BEP_m3_d',NaN),'Q_recirc_pct_nominal',NaN, ...
    'Q_recirc_max_diseno_m3_d',NaN,'Q_etapas_inferiores_m3_d',NaN,'Q_etapas_superiores_m3_d',NaN, ...
    'BEP_inferior_pct',NaN,'BEP_superior_pct',NaN,'estado_diseno','NO_EVALUADO', ...
    'estado_operativo','NO_EVALUADO','estado_secciones','SECCIONES_NO_EVALUADAS','cumple_diseno',false);
  s=struct('version',p.bes3_version,'estado_validacion',p.bes3_estado_validacion,'estado',e, ...
    'modo_operacion','BOMBA_ENCENDIDA','estado_bomba','ENCENDIDA','modo_frecuencia',p.bes3_modo_frecuencia, ...
    'frecuencia_configurada_Hz',p.bes3_frecuencia_configurada_Hz,'frecuencia_solicitada_Hz',p.frecuencia, ...
    'frecuencia_efectiva_Hz',p.frecuencia,'frecuencia_estado',frecuencia_estado_local(p), ...
    'convergido',false,'punto_operacion_valido',false,'punto_tipo','SIN_PUNTO', ...
    'aceptado_preliminar',false,'aceptado',false,'param',p,'bomba',b,'curva',c, ...
    'modelo_IPR',p.modelo_IPR,'modelo_VLP',vlp_sel,'vlp_efectivo',vlp_eff, ...
    'Ql_m3_d',0,'Qo_m3_d',0,'Qg_total_Sm3_d',0,'Q_pump_neto_m3_d',0,'Q_recirc_m3_d',0, ...
    'percent_BEP',NaN,'num_etapas_total',p.num_etapas,'etapa_toma',0, ...
    'Q_nominal_efectivo_m3_d',d.Q_nominal_efectivo_m3_d,'Q_recirc_pct_nominal',NaN, ...
    'Q_recirc_max_diseno_m3_d',NaN,'Q_etapas_inferiores_m3_d',NaN,'Q_etapas_superiores_m3_d',NaN, ...
    'BEP_inferior_pct',NaN,'BEP_superior_pct',NaN,'estado_diseno_recirculacion','NO_EVALUADO', ...
    'estado_operativo_recirculacion','NO_EVALUADO','diagnostico_recirculacion',d, ...
    'margen_nodal_bar',NaN,'rango_estado','NO_EVALUADO','rango_inferior_estado','NO_EVALUADO', ...
    'rango_superior_estado','NO_EVALUADO','gas_estado','NO_EVALUADO','refrigeracion_estado','NO_EVALUADO', ...
    'geometria',struct(),'recirculacion',struct(),'n_raices',0,'raices_m3_d',[], ...
    'barrido_Q_m3_d',[],'barrido_residuo_bar',[],'barrido_Pwf_bar',[],'barrido_Pintake_bar',[], ...
    'barrido_Pdesc_disponible_bar',[],'barrido_Pdesc_requerida_bar',[],'barrido_dP_bomba_bar',[], ...
    'barrido_dP_bomba_apagada_bar',[],'diagnostico',['BES3: ' e],'semaforos',struct([]));
endfunction
function s=series_local(ev)
  n=numel(ev);s=struct('Pwf',NaN(1,n),'Pintake',NaN(1,n),'Pdisp',NaN(1,n),'Preq',NaN(1,n),'dPpump',NaN(1,n));
  for i=1:n
    x=ev{i};if ~isstruct(x)||~isfield(x,'valido')||~x.valido,continue;endif
    s.Pwf(i)=x.Pwf_Pa;s.Pintake(i)=x.Pintake_Pa;s.dPpump(i)=x.dP_bomba_Pa;
    if isfield(x,'Pdesc_disponible_Pa'),s.Pdisp(i)=x.Pdesc_disponible_Pa;else,s.Pdisp(i)=x.Pintake_Pa+x.dP_bomba_Pa;endif
    s.Preq(i)=x.Pdesc_req_Pa;
  endfor
endfunction
function st=frecuencia_estado_local(p)
  if p.frecuencia<=0,st='BOMBA_APAGADA';
  elseif p.frecuencia<p.bes3_frecuencia_min_operativa_Hz,st='DEBAJO_MIN_OPERATIVA';
  elseif p.frecuencia>p.bes3_frecuencia_max_operativa_Hz,st='SOBRE_MAX_OPERATIVA';
  else,st='DENTRO_RANGO_OPERATIVO';endif
endfunction
function [sel,eff]=modelos_local(p)
  sel=p.modelo_VLP;eff=sel;
  try
    info=aos_vlp_info(p,p.D_bomba);if isfield(info,'seleccionado'),sel=info.seleccionado;endif;if isfield(info,'efectivo'),eff=info.efectivo;endif
  catch
  end_try_catch
endfunction
function v=num_local(s,campo,defecto)
  v=defecto;if isstruct(s)&&isfield(s,campo)&&isnumeric(s.(campo))&&~isempty(s.(campo))&&isfinite(s.(campo)(1)),v=double(s.(campo)(1));endif
endfunction
