function registro = aos_cad_hidraulica_registro_modelos()
% AOS_CAD_HIDRAULICA_REGISTRO_MODELOS Modelos disponibles para AOSCAD.
% El modulo no duplica las correlaciones VLP: las invoca desde src/core/common/vlp.
  registro = {
    struct('id', 'MONOFASICO_DARCY', ...
           'nombre', 'Darcy-Weisbach monofasico', ...
           'motor', 'AOSCAD_RED_HIDRAULICA', ...
           'estado', 'DEV1', ...
           'requiere_gas', false, ...
           'dominio', ['Liquido newtoniano; arbol y lazos Kirchhoff DEV1; ' ...
                       'DeltaP independiente de P_in']), ...
    struct('id', 'MULTIFASICO_HB', ...
           'nombre', 'Hagedorn-Brown AOS', ...
           'motor', 'vlp_HB_full', ...
           'estado', 'VALIDADO_EN_RED_DEV1', ...
           'requiere_gas', true, ...
           'dominio', 'Tramo multifasico; usa motor comun AOS; no opera en lazo DEV1'), ...
    struct('id', 'MULTIFASICO_DR', ...
           'nombre', 'Duns & Ros AOS', ...
           'motor', 'vlp_duns_ros', ...
           'estado', 'VALIDADO_EN_RED_DEV1', ...
           'requiere_gas', true, ...
           'dominio', 'Tramo multifasico; usa motor comun AOS; no opera en lazo DEV1'), ...
    struct('id', 'MULTIFASICO_SIMPLIFICADO', ...
           'nombre', 'VLP simplificado corregido AOS', ...
           'motor', 'vlp_simplified_corregida', ...
           'estado', 'FALLBACK_FISICO', ...
           'requiere_gas', true, ...
           'dominio', 'Tramo multifasico; fallback estable; no opera en lazo DEV1'), ...
    struct('id', 'AUTOMATICO', ...
           'nombre', 'Seleccion automatica', ...
           'motor', 'aos_cad_hidraulica_evaluar_tramo', ...
           'estado', 'DEV1', ...
           'requiere_gas', false, ...
           'dominio', 'Darcy si Qg=0; modelo multifasico configurado si Qg>0') ...
  };
endfunction
