function VERIFICAR_AOS_0_1_0_MENUS
% Verifica la estructura inicial del menu jerarquico AOS 0.1.0.
root = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(root, 'src')));
menus = {
  'AOS_app', ...
  'AOS_menu_GL_JGL', ...
  'AOS_menu_BES', ...
  'AOS_menu_BM', ...
  'AOS_menu_otros_sistemas', ...
  'AOS_menu_datos_pozo', ...
  'AOS_menu_intercambio', ...
  'AOS_menu_catalogos', ...
  'AOS_menu_reportes', ...
  'AOS_menu_configuracion', ...
  'AOS_exportar_ultima_corrida', ...
  'AOS_catalogos_listar_tipo' ...
};
legacy = {'JGL_menu','GL_puro_menu','BES_app','BM_menu','menu_sensibilidad', ...
          'menu_sensibilidad_BES','diseno_mandriles','calibrar'};
faltan = {};
for i = 1:numel(menus)
  if exist(menus{i}, 'file') ~= 2, faltan{end+1} = menus{i}; end %#ok<AGROW>
end
for i = 1:numel(legacy)
  if exist(legacy{i}, 'file') ~= 2, faltan{end+1} = legacy{i}; end %#ok<AGROW>
end
if ~isempty(faltan)
  fprintf('Faltan funciones:\n');
  for i = 1:numel(faltan), fprintf('  - %s\n', faltan{i}); end
  error('VERIFICACION AOS 0.1.0 MENUS: FALLIDA');
end
fprintf('VERIFICACION AOS 0.1.0 MENUS: ESTRUCTURA APROBADA.\n');
fprintf('Los submenus conservan los solvers heredados de AOS 0.0.12B.\n');
end
