function tabla = aos_report_table_mandriles(R)
% AOS_REPORT_TABLE_MANDRILES Convierte el diseno de mandriles a tabla nativa.
  tabla=struct([]);if ~isstruct(R)||~isfield(R,'valvulas')||~isstruct(R.valvulas),return;endif
  campos={'n','tipo','MD_m','TVD_m','Pc_est_bar','Pt_bar','dP_bar','puerto_mm', ...
    'capacidad_m3d','utilizacion','rating_bar','galeria_id','valvula_modelo', ...
    'Qg_perfil_m3d','Ql_perfil_m3d','modelo_tubing'};
  labels={'N','Tipo','MD','TVD','Pc apertura','Pt','Delta P','Puerto','Capacidad', ...
    'Utilizacion','Rating','Galeria ID','Valvula','Qg perfil','Ql perfil','Modelo tubing'};
  units={'','','m','m','bar','bar','bar','mm','Sm3/d','','bar','','','Sm3/d','m3/d',''};
  tabla=aos_report_table_from_structs('gl_mandriles_diseno','Diseno de mandriles y valvulas','GL', ...
    R.valvulas,campos,labels,units,'role','PRIMARY_RESULT','category','DESIGN', ...
    'priority','PRIMARY','default_mode','FULL_BODY','mandatory',true,'source','AOS_MANDRILES_SOLVER');
endfunction
