function aos_cad_hidraulica_aplicar_configuracion(cfg, silencioso)
% Guarda configuracion efectiva e invalida resultados previos si existen.
% Usa estado schema-allowed INVALIDADA_POR_EDICION; el motivo especifico
% CONFIGURACION se conserva en historial/item/advertencias.
  global CONFIG_ACTIVA;
  if nargin < 2, silencioso = false; endif
  if isempty(CONFIG_ACTIVA) || ~isstruct(CONFIG_ACTIVA) || ...
      ~isfield(CONFIG_ACTIVA, 'cad_topologia') || ...
      ~isfield(CONFIG_ACTIVA.cad_topologia, 'modelo_aoscad')
    error('AOSCAD HID: no hay modelo activo.');
  endif
  modelo = CONFIG_ACTIVA.cad_topologia.modelo_aoscad;
  if ~isfield(modelo, 'simulacion') || ~isstruct(modelo.simulacion)
    modelo.simulacion = struct();
  endif
  habia_resultados = isfield(modelo, 'tablas_resultados') && ...
                     isstruct(modelo.tablas_resultados) && ...
                     ((isfield(modelo.tablas_resultados, 'nodos') && ~isempty(modelo.tablas_resultados.nodos)) || ...
                      (isfield(modelo.tablas_resultados, 'tramos') && ~isempty(modelo.tablas_resultados.tramos)));
  modelo.simulacion.configuracion_hidraulica = cfg;
  if habia_resultados || (isfield(modelo.simulacion, 'motor') && ~isempty(modelo.simulacion.motor))
    motivo = 'La configuracion hidraulica cambio; se eliminaron los resultados anteriores.';
    opts = struct( ...
      'codigo', 'INVALIDADA_POR_EDICION', ...
      'invalidar_escena', true, ...
      'limpiar_resultados', true, ...
      'invalidar_recursos', true, ...
      'accion', 'EDITAR_CONFIGURACION_HIDRAULICA', ...
      'item_codigo', 'HID_RECALCULO_REQUERIDO', ...
      'advertencia', 'RESULTADOS_INVALIDADOS_POR_CONFIGURACION', ...
      'origen', 'CONFIGURACION_HIDRAULICA');
    [modelo, ~] = aos_cad_invalidar_simulacion(modelo, motivo, opts);
    % Reaplicar cfg (invalidar no debe perderla)
    modelo.simulacion.configuracion_hidraulica = cfg;
  endif
  CONFIG_ACTIVA.cad_topologia.modelo_aoscad = modelo;
  if ~silencioso
    fprintf('Configuracion hidraulica guardada.\n');
    if habia_resultados || (isfield(modelo.simulacion, 'estado') ...
        && strcmp(char(modelo.simulacion.estado), 'INVALIDADA_POR_EDICION'))
      fprintf('Resultados anteriores invalidados; ejecute nuevamente la simulacion.\n');
    endif
  endif
endfunction
