function ok = test_aos_cad_menu_hidraulica()
% Verifica estructura jerarquica sin abrir menus interactivos.
  ok = true;
  root = aos_cad_raiz();
  menu_publico = fullfile(root, 'src', 'menu', 'AOS_menu_cad_topologia.m');
  menu_impl = fullfile(root, 'src', 'modulos', 'cad_topo', ...
    'aos_cad_topologia_menu_impl.m');
  menu_hid = fullfile(root, 'src', 'modulos', 'cad_topo', ...
    'aos_cad_hidraulica_menu.m');
  menu_dominio = fullfile(root, 'src', 'modulos', 'cad_topo', ...
    'aos_cad_hidraulica_dominio_menu.m');
  menu_legacy = fullfile(root, 'src', 'modulos', 'cad_topo', ...
    'AOS_menu_cad_topologia.m');

  ok = check_local(ok, exist(menu_publico, 'file') == 2, ...
    'menu publico presente');
  ok = check_local(ok, exist(menu_impl, 'file') == 2, ...
    'implementacion jerarquica presente');
  ok = check_local(ok, exist(menu_hid, 'file') == 2, ...
    'submenu hidraulico presente');
  ok = check_local(ok, exist(menu_dominio, 'file') == 2, ...
    'submenu de dominio presente');
  ok = check_local(ok, exist(menu_legacy, 'file') ~= 2, ...
    'sin copia legacy sombreada del menu');

  if exist(menu_impl, 'file') == 2
    texto = fileread(menu_impl);
    ok = check_local(ok, ~isempty(strfind(texto, 'SIMULACION HIDRAULICA')), ...
      'nucleo hidraulico visible');
    ok = check_local(ok, ~isempty(strfind(texto, 'aos_cad_hidraulica_menu')), ...
      'enlace a submenu hidraulico');
  endif
  if exist(menu_hid, 'file') == 2
    texto = fileread(menu_hid);
    requeridos = { ...
      'Preparar/actualizar modelo hidraulico', ...
      'SELECCIONAR DOMINIO', ...
      'Ejecutar simulacion hidraulica', ...
      'Ver tabla de resultados nodales', ...
      'Ver tabla de resultados por tramo', ...
      'Guardar .aoscad simple', ...
      'Guardar .aoscad enriquecido'};
    for i = 1:numel(requeridos)
      ok = check_local(ok, ~isempty(strfind(texto, requeridos{i})), ...
        requeridos{i});
    endfor
  endif
endfunction

function ok = check_local(ok, condicion, mensaje)
  if condicion
    fprintf('OK  %s\n', mensaje);
  else
    fprintf(2, 'FALLO  %s\n', mensaje);
    ok = false;
  endif
endfunction
