function servicios = aos_suite_registro_servicios()
% AOS_SUITE_REGISTRO_SERVICIOS Servicios compartidos por los workbenches.
  servicios = repmat(servicio_local('', '', '', '', '', ''), 0, 1);
  servicios(end+1) = servicio_local('CASE_MANAGEMENT', 'Gestion de casos AOS', '0.2.0 DEV1', ...
    'ACTIVE_R2', 'AOS_menu_gestion_caso', ...
    'Apertura/importacion universal y contextual con prioridad del .aosdat activo.');
  servicios(end+1) = servicio_local('CORE_3D', 'AOS 3D Core', '0.0.1 R16', ...
    'ACTIVE_DEV1_CANDIDATE', 'AOS_menu_3d_core', ...
    'Escena 3D federada para pozos, redes, electricidad e instalaciones.');
  servicios(end+1) = servicio_local('AOSBCK', 'AOS Block Components', '0.1.9 R1', ...
    'BETA_R1', 'AOS_menu_aosbck', ...
    'Una geometria STEP reutilizable con metadatos, puertos e instancias por Survey o AOSCAD.');
  servicios(end+1) = servicio_local('UNITS', 'Unidades AOS', '0.1.9 R2', ...
    'ACTIVE', '', 'Sistema metrico primario con referencias imperiales.');
  servicios(end+1) = servicio_local('CATALOGS', 'Catalogos AOS', '0.1.9 R2', ...
    'ACTIVE_R2', 'AOS_menu_catalogos', 'Catalogos base, usuario y embebidos.');
  servicios(end+1) = servicio_local('REPORTING', 'Reportes AOS', '0.2.0 DEV1', ...
    'ACTIVE_DEV1', 'AOS_menu_reportes', 'Composicion transversal de tablas y contratos .aosrpt/.aoscad simples y enriquecidos.');
  servicios(end+1) = servicio_local('VALIDATION', 'Validacion AOS', '0.2.0 DEV1', ...
    'ACTIVE', '', 'Semaforos, origen de datos, advertencias y regresiones.');
endfunction

function s = servicio_local(id, nombre, version, estado, entrada, descripcion)
  disponible = isempty(entrada) || exist(entrada, 'file') == 2;
  s = struct('id', id, 'nombre', nombre, 'version', version, ...
    'estado', estado, 'entrada', entrada, 'descripcion', descripcion, ...
    'disponible', logical(disponible));
endfunction
