function r = bes3_pump_sections(Qnet_pump,Qrecirc,etapa_toma,fluido,curva,param)
% Bomba dividida: etapas inferiores procesan Qnet+Qrecirc; superiores Qnet.
  p=bes3_defaults(param);N=max(round(p.num_etapas),1);n1=min(max(round(etapa_toma),0),N);n2=N-n1;
  qg=fluido.gvf_bomba/max(1-fluido.gvf_bomba,1e-9)*max(fluido.Ql_local_m3_s,0);
  qlo=max(Qnet_pump+Qrecirc,0);qhi=max(Qnet_pump,0);
  gvflo=qg/max(qg+qlo,1e-12);gvfhi=qg/max(qg+qhi,1e-12);
  slo=bes3_stage_performance(qlo,gvflo,curva,p);shi=bes3_stage_performance(qhi,gvfhi,curva,p);
  if n1==0,slo=shi;endif
  valido=(n1==0||slo.valido)&&(n2==0||shi.valido);
  if ~valido
    r=struct('valido',false,'estado','CAUDAL_FUERA_CURVA_EN_SECCION','head_total_m',NaN,'dP_total_Pa',NaN,'P_eje_kW',NaN);return;
  endif
  rho=fluido.rho_l_kg_m3;
  H1=n1*slo.head_m;H2=n2*shi.head_m;dP1=rho*9.80665*H1;dP2=rho*9.80665*H2;
  P1=qlo*dP1/max(slo.eta,0.05)/1000;P2=qhi*dP2/max(shi.eta,0.05)/1000;
  r=struct('valido',true,'estado','OK','num_etapas_total',N,'etapa_toma',n1, ...
    'n_etapas_inferiores',n1,'n_etapas_superiores',n2, ...
    'Q_inferior_m3_s',qlo,'Q_inferior_m3_d',qlo*86400,'Q_superior_m3_s',qhi,'Q_superior_m3_d',qhi*86400, ...
    'gvf_inferior',gvflo,'gvf_superior',gvfhi,'head_inferior_m',H1,'head_superior_m',H2, ...
    'head_total_m',H1+H2,'dP_inferior_Pa',dP1,'dP_superior_Pa',dP2,'dP_total_Pa',dP1+dP2, ...
    'eta_inferior',slo.eta,'eta_superior',shi.eta,'P_eje_inferior_kW',P1,'P_eje_superior_kW',P2, ...
    'P_eje_kW',P1+P2,'Q_nominal_efectivo_m3_d',curva.Q_BEP_m3_d, ...
    'BEP_inferior_pct',100*qlo*86400/max(curva.Q_BEP_m3_d,1e-12), ...
    'BEP_superior_pct',100*qhi*86400/max(curva.Q_BEP_m3_d,1e-12), ...
    'stage_inferior',slo,'stage_superior',shi);
endfunction
