function r = bes3_electrico_apagado(param,T_amb_C)
% Estado electrico y termico coherente con motor detenido.
  p=bes3_defaults(param);if nargin<2||~isfinite(T_amb_C),T_amb_C=aos_temperatura_at_md(p,p.D_bomba)-273.15;endif
  mot=struct('P_eje_kW',0,'P_motor_kW',0,'eta',NaN,'carga',0,'rpm',0,'torque_Nm',0, ...
    'estado','BOMBA_APAGADA','potencia_nominal_kW',p.motor_pm_potencia_nominal_kW);
  cab=struct('V_superficie_V',p.voltaje_superficie_V,'V_fondo_V',p.voltaje_superficie_V, ...
    'corriente_A',0,'R_fase_ohm',0,'perdidas_kW',0,'caida_pct',0,'estado','BOMBA_APAGADA', ...
    'longitud_m',p.cable_longitud_m);
  vsd=struct('P_salida_kW',0,'P_entrada_kW',0,'eta',p.vsd_eta,'perdidas_kW',0,'estado','BOMBA_APAGADA');
  term=struct('T_ambiente_C',T_amb_C,'T_motor_C',T_amb_C,'deltaT_C',0, ...
    'margen_C',p.motor_pm_Tmax_C-T_amb_C,'velocidad_refrigeracion_m_s',0, ...
    'h_equiv_W_K',NaN,'estado','BOMBA_APAGADA');
  r=struct('motor',mot,'cable',cab,'vsd',vsd,'termica',term,'P_superficie_kW',0, ...
    'corriente_A',0,'estado','BOMBA_APAGADA','modelo','AOS_ELECTRICO_BOMBA_APAGADA');
endfunction
