function r = bes3_recirculacion_apagada()
% Capilar y refrigeracion forzada inactivos porque la bomba no genera presion ni calor.
  r=struct('estado','INACTIVA_POR_BOMBA_APAGADA','cumple',true, ...
    'Q_natural_m3_s',0,'Q_natural_m3_d',0,'Q_min_refrig_m3_s',0,'Q_min_refrig_m3_d',0, ...
    'Q_requerido_m3_s',0,'Q_requerido_m3_d',0,'Q_recirc_m3_s',0,'Q_recirc_m3_d',0, ...
    'etapa_toma',0,'velocidad_natural_m_s',0,'velocidad_total_m_s',0, ...
    'margen_presion',NaN,'Re_capilar',0,'regimen_capilar','SIN_FLUJO_FORZADO', ...
    'dP_disponible_Pa',0,'dP_capilar_Pa',0,'capilar',struct());
endfunction
