function m = aosbck_manifest_nuevo(step_archivo, meta)
% AOSBCK_MANIFEST_NUEVO Construye el contrato maestro del componente.
  if nargin < 2 || ~isstruct(meta), meta = struct(); endif
  [step_archivo, ok_step] = aos_texto_seguro(step_archivo, '');
  if ~ok_step || isempty(step_archivo) || exist(step_archivo, 'file') ~= 2
    error('AOSBCK: archivo STEP inexistente o invalido.');
  endif

  [~, base, ext] = fileparts(step_archivo);
  part = campo_texto_local(meta, 'part_number', base);
  cid = campo_texto_local(meta, 'component_id', aosbck_id_seguro(part, 'BCK'));
  ahora = datestr(now, 'yyyy-mm-dd HH:MM:SS');

  m = struct();
  m.info = struct( ...
    'schema', 'AOSBCK-0.1.9-R1', ...
    'format', 'ZIP_JSON_STEP', ...
    'canonical_engine', 'GNU_OCTAVE', ...
    'created_at', ahora, ...
    'modified_at', ahora, ...
    'purpose', 'REUSABLE_3D_COMPONENT_WITH_LIGHTWEIGHT_INSTANCES');
  m.component = struct( ...
    'component_id', cid, ...
    'component_type', campo_texto_local(meta, 'component_type', 'GENERIC_COMPONENT'), ...
    'part_number', part, ...
    'description', campo_texto_local(meta, 'description', base), ...
    'manufacturer_id', campo_texto_local(meta, 'manufacturer_id', 'UNSPECIFIED'), ...
    'supplier_id', campo_texto_local(meta, 'supplier_id', 'UNSPECIFIED'), ...
    'material_id', campo_texto_local(meta, 'material_id', 'UNSPECIFIED'), ...
    'material_description', campo_texto_local(meta, 'material_description', ''), ...
    'catalog_scope', campo_texto_local(meta, 'catalog_scope', 'PROJECT_OR_USER'));
  m.geometry = struct( ...
    'format', 'STEP', ...
    'package_path', ['geometry/' base ext], ...
    'source_file_name', [base ext], ...
    'source_file_path', step_archivo, ...
    'units', campo_texto_local(meta, 'geometry_units', 'mm'), ...
    'sha256', aosbck_hash_archivo(step_archivo), ...
    'orientation_convention', 'RIGHT_HANDED_Z_UP_QUATERNION_WXYZ', ...
    'scale', [1 1 1]);
  m.ports = {};
  m.instances = {};
  m.links = {};
  m.validation = struct('status', 'VALID', 'warnings', {{}}, ...
    'geometry_present', true, 'instance_count', 0);
endfunction

function v = campo_texto_local(s, nombre, defecto)
  v = defecto;
  if isstruct(s) && isfield(s, nombre) && ~isempty(s.(nombre))
    [candidato, ok] = aos_texto_seguro(s.(nombre), defecto);
    if ok, v = candidato; endif
  endif
endfunction
