function productos = aos_suite_registro_productos()
% AOS_SUITE_REGISTRO_PRODUCTOS Registro de bancos de trabajo AOS 0.2.0 DEV1.
% El orden coincide con la futura cinta del frame AOS 0.2.0.
  productos = repmat(producto_local('', '', '', '', '', '', '', ''), 0, 1);
  productos(end+1) = producto_local('SLA', 'AOS SLA', '0.1.9 R2', ...
    'OPERATIVO_BETA', 'AOS_menu_SLA', 'PRODUCTION', ...
    'Sistemas de levantamiento artificial y produccion de pozos.', 'ACTIVE');
  productos(end+1) = producto_local('WELLS', 'AOS Wells', '0.0.1 BETA R2', ...
    'BETA_ROADMAP', 'AOS_menu_wells', 'WELLS', ...
    'Survey, punzados, completacion, estado mecanico e integridad de pozos.', 'ACTIVE_WITH_ROADMAP');
  productos(end+1) = producto_local('CAD', 'AOS CAD', '0.0.1 DEV1 R16 CANDIDATO_REVISION_JEFE + AOSBCK R1', ...
    'DEV1', 'AOS_menu_cad_topologia', 'CAD', ...
    'Ingenieria 2D/3D, topologia, dominios y contratos .aoscad.', 'ACTIVE');
  productos(end+1) = producto_local('NETWORKS', 'AOS Networks', '0.0.1', ...
    'BETA', 'AOS_menu_networks', 'NETWORKS', ...
    'Redes hidraulicas, gas, agua, recoleccion y futuros lazos.', 'ACTIVE_WITH_ROADMAP');
  productos(end+1) = producto_local('ELECTRICAL', 'AOS Electrical', '0.0.1', ...
    'ROADMAP_CORE_ACTIVE', 'AOS_menu_electrical', 'ELECTRICAL', ...
    'Redes electricas, potencia, motores, cables, VSD y protecciones.', 'ROADMAP');
  productos(end+1) = producto_local('FACILITIES', 'AOS Facilities', '0.0.1', ...
    'ROADMAP', 'AOS_menu_facilities', 'FACILITIES', ...
    'Instalaciones de superficie, procesos, balances y restricciones.', 'ROADMAP');
  productos(end+1) = producto_local('GEOLOGY', 'AOS Geology', '0.0.1', ...
    'BETA_ROADMAP', 'AOS_menu_geology', 'GEOLOGY', ...
    'Geologia, estratigrafia, reservorio, punzados y modelo espacial.', 'ACTIVE_WITH_ROADMAP');
  productos(end+1) = producto_local('FLUIDS', 'AOS Fluids', '0.0.1', ...
    'BETA_TRANSVERSAL', 'AOS_menu_fluidos', 'FLUIDS', ...
    'PVT, composiciones y propiedades oficiales de fluidos para toda la Suite.', 'ACTIVE_WITH_ROADMAP');
  productos(end+1) = producto_local('SCADA', 'AOS SCADA', '0.0.1', ...
    'BETA', 'AOS_menu_scada', 'SCADA', ...
    'Historiales, adquisicion, eventos, alarmas y calibracion.', 'ACTIVE_WITH_ROADMAP');
  productos(end+1) = producto_local('ENVIRONMENTAL', 'AOS Environmental', '0.0.1 ENV-02', ...
    'ROADMAP_RUNTIME_SHELL', 'AOS_menu_environmental', 'ENVIRONMENTAL', ...
    'Emisiones, derrames, H2S, energia, riesgo y trazabilidad ambiental por asset_id.', 'ROADMAP_RUNTIME_SHELL');
  productos(end+1) = producto_local('MAINTENANCE', 'AOS Maintenance', '0.0.1', ...
    'ROADMAP', 'AOS_menu_maintenance', 'MAINTENANCE', ...
    'Integridad, confiabilidad, pulling, economia y ejecucion de acciones correctivas.', 'ROADMAP');
  productos(end+1) = producto_local('DATA', 'AOS Data', '0.2.0 DEV1', ...
    'BETA', 'AOS_menu_data', 'DATA', ...
    'Archivos, catalogos, API, contratos e interoperabilidad.', 'ACTIVE');
  productos(end+1) = producto_local('SOLVERS', 'AOS Solvers', '0.0.1', ...
    'TRANSVERSAL', 'AOS_menu_solvers', 'SOLVERS', ...
    'Registro y gobierno de motores hidraulicos, electricos, mecanicos y otros.', 'ACTIVE');
  productos(end+1) = producto_local('GLOBAL', 'AOS Global', '0.0.1', ...
    'CONCEPTUAL', 'AOS_menu_global', 'GLOBAL', ...
    'Orquestacion futura de bancos de trabajo, servicios y solvers.', 'ROADMAP');
  productos(end+1) = producto_local('VIEWER', 'AOS Viewer', 'Alpha36', ...
    'ALPHA', 'AOS_menu_viewer', 'VIEWER', ...
    'Visualizacion, comparacion y distribucion de resultados.', 'ACTIVE');
endfunction

function p = producto_local(id, nombre, version, estado, entrada, ribbon_group, descripcion, maturity)
  disponible = false;
  if ~isempty(entrada), disponible = (exist(entrada, 'file') == 2); endif
  p = struct('id', id, 'nombre', nombre, 'version', version, ...
    'estado', estado, 'entrada', entrada, 'ribbon_group', ribbon_group, ...
    'descripcion', descripcion, 'maturity', maturity, ...
    'disponible', logical(disponible));
endfunction
