function modulos = bm_registro_modulos()
% bm_registro_modulos - Registro extensible del modulo Bombeo Mecanico.
% AOS 0.1.3R1.1: evita modificar BM_menu para incorporar nuevos solvers.

  modulos = struct('id', {}, 'nombre', {}, 'funcion', {}, ...
                   'estado', {}, 'version', {}, 'descripcion', {});

  modulos(end+1) = crear('BM_OPERATIVO', ...
    'Simulacion de Bombeo Mecanico operativo', @BM_operativo_menu, ...
    'OPERATIVO', '0.1.3R1.1', ...
    'Flujo productivo BM integrado con configuracion, IPR, diagnosticos y reportes.');

  modulos(end+1) = crear('BM_OPERATIVO_GF3', ...
    'Simulacion de Bombeo Mecanico operativo II', @BM_operativo_GF3_menu, ...
    'OPERATIVO - GF3', 'GF3-1.4-INTEGRAL', ...
    'Aparato, sarta, LPP, barras de peso, spacing y graficas con GF3.');

  modulos(end+1) = crear('GIBBS_LAB', ...
    'Laboratorio Gibbs experimental', @gibbs_lab_menu, ...
    'EXPERIMENTAL', 'legado', ...
    'Laboratorio historico para ensayos y comparaciones.');

  modulos(end+1) = crear('GIBBS_V18', ...
    'BM Gibbs Solver Foundation v18', @gibbs18_menu, ...
    'LEGADO', 'v18', ...
    'Foundation historico conservado como referencia.');

  modulos(end+1) = crear('GIBBS_GF2', ...
    'Gibbs Foundation 2 - benchmark dorado', @gibbs2_menu, ...
    'BENCHMARK', 'GF2-GOLDEN-001', ...
    'Primer solver dinamico axial con resultado fisicamente coherente; congelado como testigo.');

  modulos(end+1) = crear('GIBBS_GF3', ...
    'Gibbs Foundation 3 - desarrollo activo', @gibbs3_menu, ...
    'BETA', 'GF3-1.0', ...
    'Solver axial sin coeficientes fisicos ocultos, con parametros centralizados y validacion.');
end

function m = crear(id, nombre, funcion, estado, version, descripcion)
  m = struct('id', id, 'nombre', nombre, 'funcion', funcion, ...
             'estado', estado, 'version', version, 'descripcion', descripcion);
end
